# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
config.ssh.insert_key = false
config.vm.provider :virtualbox do |vb|
vb.customize ["modifyvm", :id, "--memory", "1024"]
 end

 # control
 config.vm.define "Docker" do |app|
 app.vm.hostname = "Docker"
 app.vm.box = "ubuntu/trusty64"
 app.vm.network :private_network, ip: "10.0.0.27"
 end
 
 end
 
 
 
 
 

 

